name: Sync app-ads.txt

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  sync-app-ads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download source app-ads.txt
        run: |
          curl -sSL https://raw.githubusercontent.com/cleveradssolutions/App-ads.txt/main/app-ads.txt -o latest-app-ads.txt

      - name: Check if app-ads.txt has changed
        id: diffcheck
        run: |
          if ! cmp -s latest-app-ads.txt app-ads.txt; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Replace file if changed
        if: steps.diffcheck.outputs.changed == 'true'
        run: |
          mv latest-app-ads.txt app-ads.txt

      - name: Commit and push changes
        if: steps.diffcheck.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
          git add app-ads.txt
          git commit -m "Update app-ads.txt from source"
          git push
